# Site settings

title: Strata # Title of your site
email: ulisesantana@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Github blog of Ulises Santana, a web developer
  javascript oriented. This is my little place for share all my thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ulisesantana.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     ulisesantana  # Replace this with your Twitter username
github_username:      ulisesantana  # Replace this with your GitHub username
linkedin_username:      # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
