#
###################################
# Site wide configuration
####################################
#
title: Ulises' blog
email: ulisesantana@gmail.com
description: A little bit of my life
url: https://ulisesantana.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Atlantic/Canary
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ulises Santana
  avatar: leonids-logo.png
  job: "web developer"
  bio: "A little bit of my life"
  email: ulisesantana@gmail.com
  disqus-shortname:
  twitter: ulisesantana
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ulisesantana
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: ulisesantana
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
