export default {
  dahlNodeRegrets: "https://www.youtube.com/watch?v=M3BM9TB-8yA",
  work: "https://leanmind.es/",
  kentech: "https://www.kentech-sp.com",
  angular: "https://angularjs.org",
  react: "https://reactjs.org",
  node: "https://nodejs.org",
  deno: "https://deno.land",
  docker: "https://www.docker.com",
  rancher: "https://rancher.com",
  talk: "https://www.youtube.com/watch?v=Joqdb-oZjC8",
  hack4good: "https://hackforgood.net/las-palmas/",
  jsday: "https://jsdaycanarias.com",
  jsday2018: "https://2018.jsdaycanarias.com",
}
