export const GITHUB_URL = "https://github.com/ulisesantana"
export const TWITTER_URL = "https://twitter.com/ulisesantana"
export const TWITTER_USERNAME = "@ulisesantana"
export const REPLIT_URL = "https://repl.it/@ulisesantana"
export const CODESANDBOX_URL = "https://codesandbox.io/u/ulisesantana"
export const TELEGRAM_URL = "https://t.me/ulisesantana"
export const CV_URL = "/cv"
